### ISSUE TITLE
simconnect.dll fails every time

### ISSUE THREAD

**Issue by boudann** [lian/msfs2020-go#43]
Unzip to folder.
Start MSFS2020
Start a flight
Launch vfrmap.exe
Nothing happens.
Open command prompt, launch vfrmap.exe, get:
>vfrmap -verbose

msfs2020-go/vfrmap
  readme: https://github.com/lian/msfs2020-go/blob/master/vfrmap/README.md
  issues: https://github.com/lian/msfs2020-go/issues
  version: v0.0.7 (2020-09-05_04:33:49)

panic: Failed to load C:\Users\dannb\Downloads\vfrmap-win64-v0.0.7\SimConnect.dll: The specified module could not be found.

goroutine 1 [running]:
main.main()
        /users/lian/prj/go/lian/msfs2020-go/vfrmap/main.go:115 +0x2125

The file is there:
Directory of C:\Users\dannb\Downloads\vfrmap-win64-v0.0.7

09/14/2020  08:22 PM    <DIR>          .
09/14/2020  08:22 PM    <DIR>          ..
09/14/2020  08:22 PM            58,368 SimConnect.dll
09/05/2020  06:33 AM         5,375,488 vfrmap.exe
               2 File(s)      5,433,856 bytes
               2 Dir(s)  737,648,037,888 bytes free

**Comment by lian** [comment]
thanks for the detailed report. i have not encountered this issue, or seen any reports of it so far. and only have little windows knowledge :)

can you try a different folder? maybe (pure guess) windows doesn't like dll's in Downloads folder?

otherwise hope someone else knows what the issue is.

**Comment by boudann** [comment]
Yeah, it's a weird issue.  I had this running fine on a different
computer.  Tried on this new one, no go.  I thought the same thing about
trying in another folder, but didn't work.  Tried running as administrator,
tried powershell vs cmd prompt, tried unzipping w/ 7zip instead of the
built in Windows archiver.  No luck.  This is a brand new fresh install of
Win10.  I'll keep trying stuff.
thanks,
Brian

**Comment by Bi0force1** [comment]
When you launch the .exe from a new folder it should insert the simconnect.dll file into that folder. I am guessing that part isnt happening?

I haven't learned enough about the code to know where that .dll is coming from. 

If you copy the file from the PC where its working, and place it in the same folder as the .exe on your new machine, i assume it'll work as a workaround.

**Comment by zazaboeing** [comment]
Unfortunately I'm having the same issue after my brand new computer format. 

panic: Failed to load D:\MSFS\Community\-- vfrmap-win64-v0.0.7\SimConnect.dll: The specified module could not be found.

goroutine 1 [running]:
main.main()
        /users/lian/prj/go/lian/msfs2020-go/vfrmap/main.go:115 +0x2125

**Comment by Bi0force1** [comment]
I've been trying to replicate this to help find a solution, but i cant seem to replicate it.

Can anyone check their event Logs and see if Windows is blocking the simconnect.dll file from being tossed into the folder with the .exe?

**Comment by lian** [comment]
@Bi0force1 doesn't his first comment show that dll was written `2 File(s)` ?

thank you for helping to solve this!!

**Comment by boudann** [comment]
The dll file gets written into the directory the first time vfrmap.exe is executed.  I showed this in my initial comment.  
Directory of C:\Users\dannb\Downloads\vfrmap-win64-v0.0.7

09/14/2020 08:22 PM

.
09/14/2020 08:22 PM ..
**09/14/2020 08:22 PM 58,368 SimConnect.dll**
09/05/2020 06:33 AM 5,375,488 vfrmap.exe
2 File(s) 5,433,856 bytes
2 Dir(s) 737,648,037,888 bytes free

I verified AV is not quarantining and same issue persists w/ all default Windows Defender junk turned off.

**Comment by Bi0force1** [comment]
Lets look at 2 things.

1. Right click on simconnect.dll, on the General tab is there a warning "this program is blocked"?  If so, is there a unblock button that you can click.

2. In the same properties file, go to Security tab, do you have permissions checked for:   Full control, Modify, Read and Execute, Read, and Write?

**Comment by zazaboeing** [comment]
Hi! 
1 - There's no such warning, and I've made sure to have ownership of the file, no windows defender, firewall or antivirus at all is interfering, those are all turned off.
2 - All those are checked!

Tried many different settings now, every compatibility test and it's definitely not working. It opens momentarily (for a very brief milisecond) the command prompt screen and closes silently. No windows event viewer message also.

**Comment by msfsuser** [comment]
Hi,
I am having the exact same issue (see post one) on a brand new HP-Omen W10.
(Other tan that - this is the ONE tool vor MSFS that I was hoping for)

**Comment by erichump** [comment]
You need the "Microsoft Visual C++ Redistributable for Visual Studio 2015". SimConnect.dll is compiled to link dynamically to the VC runtime.

**Comment by msfsuser** [comment]
Yes, that worked. Just had to run the latest vc_redist.x64.exe (not sure about posting links here) which added the 2015 files. Those are apparently missing on new systems.    
Thanks!!

**Comment by lian** [comment]
@erichump awesome, thank you for debugging this! iirc steam auto installed vc_redist.x64.exe on install for me.

**Comment by bigpannard** [comment]
> You need the "Microsoft Visual C++ Redistributable for Visual Studio 2015". SimConnect.dll is compiled to link dynamically to the VC runtime.

i've got the same issue but vc_redist.x64 is already installed. It's a fresh windows installation do we have some ideas for me

**Comment by reanorius** [comment]
Can someone fix vfrmap.exe? It stopped working after the yesterday's MSFS 2024 update. I am ready to pay 50$ if you can fix it and then let me know how to fix it when the MSFS 2024 updates again.
